### ISSUE TITLE
Webhook Payload Event Name - Order Has Been Changed Issue 

### ISSUE THREAD

**Issue by Koshalgarg155** [VirtoCommerce/vc-module-webhooks#59]
Hi,
I am facing an issue with the webhook payload Event Name - Order Has Been Changed.
This issue happened when I did upgrade my platform from 3.66 to 3.240.
I am using Webhook Module 3.201 

- When this webhook gets triggered it does not send the changed entries in the payload and there is no option for changed entries in additional field

Thanks

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8176 has been created

**Comment by Dan-BV** [comment]
@Koshalgarg155, Hi!
We would appreciate it if you could describe the problem in more detail. It would help us a lot if you could describe the steps to reproduce it, as well as the actual and expected results.

**Comment by Koshalgarg155** [comment]
Hi @Dan-BV,
When I updated the platform from 3.66 to 3.240, then I am facing issue with the order changed event payload.
**Expected Payload** -  It should have changed entries i.e new entry and old entry of order payload
{
  "EventId": "VirtoCommerce.OrdersModule.Core.Events.OrderChangedEvent",
  "Attempt": 2,
  "EventBody": {
    "changedEntries": [
      {
        "entryState": "Modified",
        "newEntry": {
              "id": "4361da8a-ab8a-43b3-855e-6b421ea77ccf",
              "status" : "New"
            }
        },
        "oldEntry": {
    "id": "4361da8a-ab8a-43b3-855e-6b421ea77ccf",
     "Status": "Processing"
  }
}

**Actual Payload** - It is giving only new entries of order payload 
 {
  "EventId": "VirtoCommerce.OrdersModule.Core.Events.OrderChangedEvent",
  "Attempt": 1,
  "EventBody": "[{\"ObjectType\":\"VirtoCommerce.OrdersModule.Core.Model.CustomerOrder\",\"Id\":\"db12d5ae-6aa4-4ae1-ab1a-c96a068043ad\"}]"
}


Thanks for the response

**Comment by Dan-BV** [comment]
@Koshalgarg155 What version of the module did you use before? There have been significant changes in recent versions. Now the required fields must be added directly in the admin panel. 
![image](https://user-images.githubusercontent.com/110034308/189907429-15b51627-059c-4940-87ca-e22b3ba6c180.png)

```
{
  "EventId": "VirtoCommerce.OrdersModule.Core.Events.OrderChangedEvent",
  "Attempt": 1,
  "EventBody": "[{\"ObjectType\":\"VirtoCommerce.OrdersModule.Core.Model.CustomerOrder\",\"Status\":\"New\",\"CustomerId\":\"c263a9c3-68ed-4c05-a8a7-d389caa4ffdd\",\"IsApproved\":false,\"CustomerName\":\"Anonymous\",\"Id\":\"1833318a03a94d27acec0533f96340fb\"}]"
}
```


The documentation is available here: https://github.com/VirtoCommerce/vc-module-webhooks/blob/dev/docs/index.md#configuring-webhooks

**Comment by Koshalgarg155** [comment]
@Dan-BV, I was using 3.1 but now I have upgraded it with platform to 3.201.
I have checked options but there is no option for changed entries like what was the old payload and what is the new payload there is only a new payload. Please check the expected payload : **changedEntries** . Then status is according to the entry like old entry Status is :- Processing and new Entry status is :- New

**Comment by Koshalgarg155** [comment]
Hi @Dan-BV @OlegoO,
this issue is the expected payload please check the expected payload and suggest a solution
Thanks

**Comment by rahul-reveation** [comment]
Hi @Dan-BV @OlegoO 

I just would like to add more context to the issue. 

We recently upgraded the webhook module from 3.1.0 to 3.201 as part of the Virto platform upgrade. After the upgradation of the module, the webhook NO longer fires the same payload as it was in 3.1.0.  It's missing the changed entries field which used to show both old and new object changes which were crucial for our logic to work. The new version only includes the new entry in the array. There is no `oldEntry` field as @Koshalgarg155  mentioned in the follow-up messages. 

The issue seems to be caused by the logic added to `DomainEvent.GetEntityWithInterface()`  method.  For each loop seems to be filtering out oldEntry and include only newEntry  ` .Where(x => x.Name.EqualsInvariant(nameof(GenericChangedEntry<TResult>.NewEntry)))`. 

https://github.com/VirtoCommerce/vc-module-webhooks/compare/3.1.0...3.201.0#diff-17362562cf300526a78199485eb6347b101163a9b8772b9d07e28250870125a5R32

```
                   foreach (var collectionObject in enumerable)
                  {
                      result.AddRange(collectionObject.GetType().GetProperties()
                                                    .Where(x => x.Name.EqualsInvariant(nameof(GenericChangedEntry<TResult>.NewEntry)))
                                                    .Select(p => p.GetValue(collectionObject))
                                                    .OfType<TResult>());
                  }
```


If this is breaking changes in a recent version, please recommend the alternative to identify what has changed in the entity.

**Comment by OlegoO** [comment]
@rahul-reveation  @Koshalgarg155 
please download and test alfa from https://github.com/VirtoCommerce/vc-module-webhooks/pull/60

For this configuration
![image](https://user-images.githubusercontent.com/7639413/192807643-b8aeb197-76fd-4d99-8c07-69a9fdfdb1d8.png)

I receive 
![image](https://user-images.githubusercontent.com/7639413/192804045-d8ff9944-abb7-4343-b2c8-dd76f396a7f7.png)

It should provide access to previous values for selected fields in "__Previous"

Your feedback is welcome

**Comment by Koshalgarg155** [comment]
Thanks @OlegoO. We will check it out

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-webhooks/releases/tag/3.202.0
